function quit()
	exit
endf

main as Gui
Window {
	.title:'ola mundo como estão'
	.top:10
	.left:100
	.width:300
	.height:300
	.visible:true
	.state:1
	Button {
		.On.Click:quit()
		.title:'quit'
		.top:50
		.left:50
		.width:100
		.height:30
		.visible:true
	}
		Button {
		.On.Click:quit()
		.title:'quit'
		.top:100
		.left:50
		.width:100
		.height:30
		.visible:true
	}
		Button {
		.On.Click:quit()
		.title:'quit'
		.top:150
		.left:50
		.width:100
		.height:30
		.visible:true
	}
}




